# Generated by Django 5.0.4 on 2024-07-25 06:15

from django.db import migrations

from api.constants import _TaskStatus


def migrate_status_to_status_history_point(apps, schema_editor):
    Task = apps.get_model('api', 'Task')
    StatusHistoryPoint = apps.get_model('api', 'StatusHistoryPoint')

    for task in Task.objects.all():
        new_status = None
        for s in _TaskStatus:
            if s.label == task.status:
                new_status = s
                break
        if new_status is None:
            new_status = _TaskStatus.UNKNOWN

        created_at = task.latest_update or task.submitted_at
        StatusHistoryPoint.objects.create(
            task=task,
            status=new_status,
            created_at=created_at,
        )


def reverse_migrate_status_to_status_history_point(apps, schema_editor):
    StatusHistoryPoint = apps.get_model('api', 'StatusHistoryPoint')
    StatusHistoryPoint.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_statushistorypoint_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_status_to_status_history_point, reverse_migrate_status_to_status_history_point),
    ]
