# Generated by Django 5.0.4 on 2024-09-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_migrate_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
