# Generated by Django 5.0.4 on 2024-09-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempTag',
            new_name='Tag',
        )
    ]
