# Generated by Django 5.0.4 on 2024-09-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_temptag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tasks',
            field=models.ManyToManyField(related_name='tags', to='api.task'),
        ),
    ]
