# Generated by Django 5.1.7 on 2025-06-22 20:08

from django.db import migrations, models
from django.db.models import Q, OuterRef, Subquery


def migrate_status_add_queued_status(apps, schema_editor):
    StatusHistoryPoint = apps.get_model('api', 'StatusHistoryPoint')
    StatusHistoryPoint.objects.filter(status__gte=3).update(status=models.F('status') + 1)


def reverse_migrate_status_remove_queued_status(apps, schema_editor):
    StatusHistoryPoint = apps.get_model('api', 'StatusHistoryPoint')
    # Yeah, I know, it makes queued executions automatically to become scheduled which may not be true
    # I don't expect to have any need to retrack this feature, so I guess it's a risk that we're willing to take
    StatusHistoryPoint.objects.filter(status__gte=4).update(status=models.F('status') - 1)


def migrate_unref_running_tasks(apps, schema_editor):
    Task = apps.get_model('api', 'Task')
    StatusHistoryPoint = apps.get_model('api', 'StatusHistoryPoint')

    inner_qs = StatusHistoryPoint.objects.filter(status__gte=0, status__lte=5, task=OuterRef('pk')).order_by('-status',
                                                                                                           '-created_at')
    running_tasks = Task.objects.annotate(latest_status=Subquery(inner_qs.values('status')[:1])).filter(
        latest_status__in=[6, 7, 8])
    for t in running_tasks:
        StatusHistoryPoint.objects.create(task=t, status=-1)


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0010_alter_tag_tasks'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='statushistorypoint',
            name='status_history_enum',
        ),
        migrations.RenameField(model_name='task', old_name='task_id', new_name='backend_ref'),
        migrations.AlterField(model_name='task', name='backend_ref', field=models.CharField(
            help_text='Task ID that assigned to task by underlying API',
            max_length=255
        )),
        migrations.AddField(
            model_name='task',
            name='manager_name',
            field=models.CharField(default='', help_text='Manager name handling the execution', max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_unref_running_tasks, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='statushistorypoint',
            name='status',
            field=models.IntegerField(
                choices=[(-1, 'UNKNOWN'), (0, 'SUBMITTED'), (1, 'APPROVED'), (2, 'REJECTED'), (3, 'QUEUED'),
                         (4, 'SCHEDULED'), (5, 'INITIALIZING'), (6, 'RUNNING'), (7, 'COMPLETED'), (8, 'ERROR'),
                         (9, 'CANCELED')]),
        ),
        migrations.RunPython(
            migrate_status_add_queued_status, reverse_code=reverse_migrate_status_remove_queued_status
        ),
        migrations.AddConstraint(
            model_name='statushistorypoint',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', [-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])),
                                              name='status_history_enum'),
        ),
    ]
