# Generated by Django 5.2.3 on 2025-06-23 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowstatuslog',
            old_name='value',
            new_name='status',
        ),
    ]
