# Generated by Django 5.0.4 on 2024-07-16 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_active_disk_gb', models.PositiveSmallIntegerField(null=True)),
                ('max_active_ram_gb', models.PositiveSmallIntegerField(null=True)),
                ('max_active_cpu_cores', models.PositiveSmallIntegerField(null=True)),
                ('max_ram_gb_request', models.PositiveSmallIntegerField(null=True)),
                ('max_disk_gb_request', models.PositiveSmallIntegerField(null=True)),
                ('max_cpu_cores_request', models.PositiveSmallIntegerField(null=True)),
                ('max_active_tasks', models.PositiveSmallIntegerField(null=True)),
                ('total_tasks', models.PositiveIntegerField(null=True)),
                ('max_executors_request', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContextQuotas',
            fields=[
                ('quotas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quotas.quotas')),
                ('context', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='api.context')),
            ],
            bases=('quotas.quotas',),
        ),
        migrations.CreateModel(
            name='ParticipationQuotas',
            fields=[
                ('quotas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quotas.quotas')),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='api.participation')),
            ],
            bases=('quotas.quotas',),
        ),
    ]
